# Default webserv configuration

server {
    listen 8080;
    server_name localhost;
    
    root ./www;
    index index.html;
    
    client_max_body_size 5M;
    
    error_page 404 /errors/404.html;
    error_page 500 /errors/500.html;
    error_page 501 /errors/501.html;
    error_page 405 /errors/405.html;
    
    location /
    {
        allowed_methods GET;
        autoindex off;
    }
    
    location /uploads
    {
        allowed_methods POST DELETE GET;
        client_max_body_size 500M;
        autoindex on;
    }
    
    location /errors
    {
        allowed_methods GET;
        autoindex on;
    }

    location /cgi_bin
    {
        allowed_methods GET POST DELETE;
        root ./www/cgi_bin;
        cgi_pass .py    /usr/bin/python3;
        cgi_pass .php   /usr/bin/php-cgi;
    }

    location /hello
    {
        return 301 /errors/405.html;
    }

}

server {
    listen 8081;
    server_name localhost;

    root ./www1;
    index index.html;

    client_max_body_size 2M;

    location / {
        allowed_methods GET;
        autoindex on;
    }
}

server {
    listen 8082;
    server_name localhost;

    root ./www2;
    index index.html;

    client_max_body_size 2M;

    location / {
        allowed_methods GET;
        autoindex on;
    }

    location /public/ {
        allowed_methods GET;
        autoindex on;
    }
}
